/* data.js — Shanghai Map Beta1, generated by _build_data.py
 * Source: prototype-map/stops_v3.json (26 stops, 15 exact / 11 approx)
 * Generated: 2026-05-12T13:31:10
 * Schema: window.__DATA__ = { STOPS, TIMESTAMPS, BUILD_FREEZE_DATE, BUILD_ID, VARIANT }
 */
(function () {
  'use strict';
  var STOPS = [
  {
    "id": 0,
    "slug": "hotel",
    "nameKr": "Atour 호텔 (인민광장 · 난징루 보행가)",
    "nameCn": "上海人民广场南京路步行街亚朵酒店",
    "lat": 31.2376,
    "lng": 121.4818,
    "category": "hotel",
    "categoryIconKey": "bed",
    "tier": "X",
    "icon": "🏨",
    "desc": "5/22(목) 체크인 → 5/25(일) 04:30 체크아웃. 인민광장·南京路步行街 인접. 외탄 도보 10–15분, 인민광장 도보 5분, 南京东路역(2호선·10호선) 도보 5분.",
    "videos": [],
    "approx": true,
    "imgQuery": "atour hotel shanghai bund",
    "weightedScore": null,
    "rawCount": null,
    "source": "notion",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null,
    "address": "586 Ningbo Rd, Huangpu, Shanghai 200001 / 上海市黄浦区宁波路586号",
    "isBaseline": true
  },
  {
    "id": 1,
    "slug": "yuyuan",
    "nameKr": "위위안 (예원)",
    "nameCn": "豫园 · Yu Garden",
    "lat": 31.2266,
    "lng": 121.492,
    "category": "landmark",
    "categoryIconKey": "landmark",
    "tier": "A",
    "icon": "🌿",
    "desc": "1500년대 명나라 정원. 9번 꺾인 회랑(강시 막기). 푸드코트 빨대만두 since 1900. 야경 추천. 1–1.5시간.",
    "videos": [
      {
        "num": 3,
        "channel": "JTBC Life"
      },
      {
        "num": 5,
        "channel": "육식맨"
      },
      {
        "num": 7,
        "channel": "침착맨"
      },
      {
        "num": 9,
        "channel": "김숙티비"
      },
      {
        "num": 10,
        "channel": "또떠나는남자"
      },
      {
        "num": 14,
        "channel": "노마드션"
      },
      {
        "num": 17,
        "channel": "캡틴따거"
      }
    ],
    "approx": false,
    "imgQuery": "yu garden shanghai 豫园 night",
    "weightedScore": 16400,
    "rawCount": 117,
    "source": "youtube+suvin",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  },
  {
    "id": 2,
    "slug": "bund",
    "nameKr": "와이탄 (외탄)",
    "nameCn": "外滩 · The Bund",
    "lat": 31.2397,
    "lng": 121.4905,
    "category": "landmark",
    "categoryIconKey": "landmark",
    "tier": "A",
    "icon": "🌃",
    "desc": "200년 전 영국·프랑스 강제 개항지. 황푸강 야경. 호텔 도보 10-15분. 4편 영상의 오프닝 장소. 식민지 시대 서양 건축 vs 푸둥 마천루 대비.",
    "videos": [
      {
        "num": 2,
        "channel": "걍밍경"
      },
      {
        "num": 3,
        "channel": "JTBC Life"
      },
      {
        "num": 5,
        "channel": "육식맨"
      },
      {
        "num": 6,
        "channel": "침착맨"
      },
      {
        "num": 7,
        "channel": "침착맨"
      },
      {
        "num": 10,
        "channel": "또떠나는남자"
      },
      {
        "num": 12,
        "channel": "캡틴따거"
      },
      {
        "num": 14,
        "channel": "노마드션"
      },
      {
        "num": 17,
        "channel": "캡틴따거"
      }
    ],
    "approx": false,
    "imgQuery": "shanghai bund night skyline waitan",
    "weightedScore": 4392,
    "rawCount": 31,
    "source": "youtube+suvin",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  },
  {
    "id": 3,
    "slug": "pearl",
    "nameKr": "동방명주",
    "nameCn": "东方明珠塔 · Oriental Pearl",
    "lat": 31.2397,
    "lng": 121.4995,
    "category": "landmark",
    "categoryIconKey": "landmark",
    "tier": "A",
    "icon": "🗼",
    "desc": "푸둥 송신탑. 핑크→마젠타 색 변화. 황포강 유람선에서 가장 잘 보임. 4편 영상의 클로징 장소.",
    "videos": [
      {
        "num": 2,
        "channel": "걍밍경"
      },
      {
        "num": 3,
        "channel": "JTBC Life"
      },
      {
        "num": 5,
        "channel": "육식맨"
      },
      {
        "num": 6,
        "channel": "침착맨"
      },
      {
        "num": 7,
        "channel": "침착맨"
      },
      {
        "num": 10,
        "channel": "또떠나는남자"
      },
      {
        "num": 12,
        "channel": "캡틴따거"
      },
      {
        "num": 17,
        "channel": "캡틴따거"
      }
    ],
    "approx": false,
    "imgQuery": "oriental pearl tower shanghai night illumination",
    "weightedScore": 4215,
    "rawCount": 27,
    "source": "youtube+suvin",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  },
  {
    "id": 4,
    "slug": "shanghai_tower",
    "nameKr": "상하이 타워",
    "nameCn": "上海中心大厦 · Shanghai Tower",
    "lat": 31.2336,
    "lng": 121.505,
    "category": "landmark",
    "categoryIconKey": "landmark",
    "tier": "A",
    "icon": "🏙️",
    "desc": "꺾여 돌아가는 디자인. 푸둥 최고층. 118층 전망대 입장료 180위안. 침착맨 메인 랜드마크.",
    "videos": [
      {
        "num": 6,
        "channel": "침착맨"
      },
      {
        "num": 7,
        "channel": "침착맨"
      }
    ],
    "approx": false,
    "imgQuery": "上海中心大厦 Shanghai Tower 上海陆家嘴 building photo skyscraper",
    "weightedScore": 1689,
    "rawCount": 13,
    "source": "youtube+suvin",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  },
  {
    "id": 5,
    "slug": "jinmao",
    "nameKr": "진마오 타워",
    "nameCn": "金茂大厦 · Jin Mao",
    "lat": 31.2358,
    "lng": 121.5009,
    "category": "landmark",
    "categoryIconKey": "landmark",
    "tier": "B",
    "icon": "🏢",
    "desc": "그랜드 하야트 호텔 51층~ 입주. 침착맨 가족 숙박지. 동방명주 다음으로 지어진 푸둥 빌딩.",
    "videos": [
      {
        "num": 3,
        "channel": "JTBC Life"
      },
      {
        "num": 6,
        "channel": "침착맨"
      }
    ],
    "approx": false,
    "imgQuery": "jin mao tower shanghai pudong",
    "weightedScore": 1523,
    "rawCount": 14,
    "source": "youtube",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  },
  {
    "id": 6,
    "slug": "nanjing_rd",
    "nameKr": "난징동루",
    "nameCn": "南京东路",
    "lat": 31.2342,
    "lng": 121.4798,
    "category": "landmark",
    "categoryIconKey": "landmark",
    "tier": "B",
    "icon": "🛍️",
    "desc": "외국인의 명동. 보행자 거리. 호텔에서 도보 10분. 침착맨 후편 산책 코스.",
    "videos": [
      {
        "num": 7,
        "channel": "침착맨"
      }
    ],
    "approx": false,
    "imgQuery": "nanjing road shanghai pedestrian street night",
    "weightedScore": 516,
    "rawCount": 4,
    "source": "youtube",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  },
  {
    "id": 7,
    "slug": "xintiandi",
    "nameKr": "신톈디",
    "nameCn": "新天地 · Xintiandi",
    "lat": 31.2202,
    "lng": 121.4753,
    "category": "landmark",
    "categoryIconKey": "landmark",
    "tier": "B",
    "icon": "🏘️",
    "desc": "옛 프랑스 카페 문화 + 유럽식 건물. 봉록수 동상. 음료 15,000원 비쌈. 임시정부 청사 근처.",
    "videos": [
      {
        "num": 7,
        "channel": "침착맨"
      }
    ],
    "approx": false,
    "imgQuery": "Xintiandi Shanghai shikumen 石库门 plaza night european buildings",
    "weightedScore": 258,
    "rawCount": 2,
    "source": "youtube",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  },
  {
    "id": 8,
    "slug": "starbucks",
    "nameKr": "스타벅스 리저브 로스터리",
    "nameCn": "Starbucks Reserve Roastery",
    "lat": 31.223,
    "lng": 121.4575,
    "category": "landmark",
    "categoryIconKey": "landmark",
    "tier": "B",
    "icon": "☕",
    "desc": "세계 3번째 큰 매장 (2017 오픈). 시그니처 음료 '상하이 노스탤지아' (율무차 같은 고소 커피). 합석 문화. 박명수 ep.273 추천.",
    "videos": [
      {
        "num": 1,
        "channel": "할명수"
      }
    ],
    "approx": false,
    "imgQuery": "starbucks reserve roastery shanghai interior",
    "weightedScore": null,
    "rawCount": null,
    "source": "youtube",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  },
  {
    "id": 9,
    "slug": "renmin_sq",
    "nameKr": "인민광장",
    "nameCn": "人民广场 · People's Square",
    "lat": 31.2304,
    "lng": 121.4737,
    "category": "landmark",
    "categoryIconKey": "landmark",
    "tier": "B",
    "icon": "🎪",
    "desc": "도심 한가운데. 호텔에서 도보 5분. 캡틴따거 영상에서 파기름국수 가게 위치 기준점.",
    "videos": [
      {
        "num": 17,
        "channel": "캡틴따거"
      }
    ],
    "approx": false,
    "imgQuery": "people's square shanghai 人民广场",
    "weightedScore": null,
    "rawCount": null,
    "source": "youtube",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  },
  {
    "id": 10,
    "slug": "wukang",
    "nameKr": "우캉맨션",
    "nameCn": "武康大楼 · Wukang Mansion",
    "lat": 31.2098,
    "lng": 121.4459,
    "category": "landmark",
    "categoryIconKey": "landmark",
    "tier": "B",
    "icon": "🏛️",
    "desc": "1924년 르네상스 양식. 영화 〈색,계〉 촬영지. 인증샷 국룰. 주말 사람 너무 많음, 평일 추천. 길 건너 사진작가 1,800–3,600원에 보정까지.",
    "videos": [
      {
        "num": 5,
        "channel": "육식맨"
      }
    ],
    "approx": false,
    "imgQuery": "wukang mansion shanghai 武康大楼",
    "weightedScore": null,
    "rawCount": null,
    "source": "youtube+suvin",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  },
  {
    "id": 100,
    "slug": "jesse",
    "nameKr": "Jesse Restaurant (장국영 단골)",
    "nameCn": "老吉士 · Jesse Restaurant",
    "lat": 31.2167,
    "lng": 121.447,
    "category": "restaurant",
    "categoryIconKey": "utensils",
    "tier": "B",
    "icon": "🍽️",
    "desc": "장국영이 즐겨 찾던 상하이 가정식. 우캉맨션 인근. 홍소육 ★★★ (육식맨 \"동파육보다 맛있다\"). 파기름국수 박살나는 맛.",
    "videos": [
      {
        "num": 5,
        "channel": "육식맨"
      }
    ],
    "approx": true,
    "imgQuery": "jesse restaurant shanghai 老吉士",
    "weightedScore": null,
    "rawCount": null,
    "source": "youtube",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  },
  {
    "id": 101,
    "slug": "dahuchun",
    "nameKr": "따후춘 大壶春 (성젠 미쉐린)",
    "nameCn": "大壶春 · 17년 연속 빕구르망",
    "lat": 31.24,
    "lng": 121.481,
    "category": "restaurant",
    "categoryIconKey": "utensils",
    "tier": "B",
    "icon": "🥟",
    "desc": "2018-2024 미쉐린 빕구르망 17년 연속. 바닥 바삭+위 촉촉 성젠. 갈비맛 만두 한 조각 500원. 새우/게살 만두 추가.",
    "videos": [
      {
        "num": 5,
        "channel": "육식맨"
      }
    ],
    "approx": true,
    "imgQuery": "dahuchun shanghai 大壶春 shengjianbao",
    "weightedScore": null,
    "rawCount": null,
    "source": "youtube",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  },
  {
    "id": 102,
    "slug": "local_shengjian",
    "nameKr": "동네 성젠 가게",
    "nameCn": "生煎包 (동네)",
    "lat": 31.231,
    "lng": 121.479,
    "category": "restaurant",
    "categoryIconKey": "utensils",
    "tier": "B",
    "icon": "🥟",
    "desc": "캡틴따거 추천: \"관광지 말고 사람 사는 동네 가서 갓 튀긴 거 5분 기다렸다 먹기\". 호텔 근처 추정 위치.",
    "videos": [
      {
        "num": 17,
        "channel": "캡틴따거"
      }
    ],
    "approx": true,
    "imgQuery": "生煎包 上海街头 老店 빨대만두 굽는 모습 노포",
    "weightedScore": null,
    "rawCount": null,
    "source": "youtube",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  },
  {
    "id": 103,
    "slug": "feidachu",
    "nameKr": "페이타추 (호남 매운 요리)",
    "nameCn": "费大厨辣椒炒肉",
    "lat": 31.23,
    "lng": 121.475,
    "category": "restaurant",
    "categoryIconKey": "utensils",
    "tier": "B",
    "icon": "🌶️",
    "desc": "라쟈오라우(고추+돼지 볶음) 밥솥째 등장. 한국식 화끈한 매운맛. 빠니보틀 콜라보 영상 메인 식당.",
    "videos": [
      {
        "num": 17,
        "channel": "캡틴따거"
      }
    ],
    "approx": true,
    "imgQuery": "fei da chu hunan spicy pork 费大厨",
    "weightedScore": null,
    "rawCount": null,
    "source": "youtube",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  },
  {
    "id": 200,
    "slug": "diandeqi_yuyuan",
    "nameKr": "점도덕 예원점 (딤섬 ⭐⭐⭐⭐⭐)",
    "nameCn": "点都德 · 豫园店",
    "lat": 31.2275,
    "lng": 121.4935,
    "category": "restaurant",
    "categoryIconKey": "utensils",
    "tier": "B",
    "icon": "🥟",
    "desc": "수빈 추천 #1. 예원역 1번 출구 도보 5분. 새우딤섬·샤오롱바오·홍미창펀·쇠고기볶음면. \"비주얼도 맛도 완벽💯\". 웨이팅 있음 — 일찍 가기. 09:00–22:00.",
    "videos": [],
    "approx": true,
    "imgQuery": "点都德 dim sum 새우딤섬 샤오롱바오 음식",
    "weightedScore": null,
    "rawCount": null,
    "source": "suvin",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  },
  {
    "id": 201,
    "slug": "hanshe",
    "nameKr": "한서식당 (베이징덕)",
    "nameCn": "漢舍中国菜 · Hakkasan style",
    "lat": 31.228,
    "lng": 121.4915,
    "category": "restaurant",
    "categoryIconKey": "utensils",
    "tier": "B",
    "icon": "🦆",
    "desc": "수빈 \"숙소 옆 베이징덕 집\" 후보. 미슐랭 가이드 추천 + 흑진주 1다이아. 시그니처 = 과일숯 북경오리, 바삭한 껍질+촉촉한 속살. (수빈 확인 필요)",
    "videos": [],
    "approx": true,
    "imgQuery": "漢舍中国菜 Han She peking duck 북경오리 미슐랭",
    "weightedScore": null,
    "rawCount": null,
    "source": "suvin",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  },
  {
    "id": 202,
    "slug": "nanxiang",
    "nameKr": "남상만두 (난샹 만터우뎬)",
    "nameCn": "南翔馒头店 · 100년 전통",
    "lat": 31.2266,
    "lng": 121.492,
    "category": "restaurant",
    "categoryIconKey": "utensils",
    "tier": "B",
    "icon": "🥟",
    "desc": "수빈 추천. 예원 정문 앞. 100년 전통 샤오롱바오. 미슐랭 빕구르망. (육식맨 영상에서 난샹 본점 방문 — 본점은 외곽 古猗園)",
    "videos": [
      {
        "num": 5,
        "channel": "육식맨"
      }
    ],
    "approx": true,
    "imgQuery": "nanxiang mantou dian xiaolongbao 南翔",
    "weightedScore": null,
    "rawCount": null,
    "source": "youtube",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  },
  {
    "id": 203,
    "slug": "haidilao",
    "nameKr": "하이디라오 (훠궈)",
    "nameCn": "海底捞火锅",
    "lat": 31.228,
    "lng": 121.485,
    "category": "restaurant",
    "categoryIconKey": "utensils",
    "tier": "B",
    "icon": "🍲",
    "desc": "수빈 추천. 중국 최고 훠궈 체인. 예원 도보 10분 지점 추정. 토마토탕·마라탕 인기. 직원 친절·기다리는 동안 네일/마사지 무료.",
    "videos": [
      {
        "num": 1,
        "channel": "할명수"
      },
      {
        "num": 7,
        "channel": "침착맨"
      }
    ],
    "approx": true,
    "imgQuery": "haidilao hotpot shanghai 海底捞",
    "weightedScore": 1051,
    "rawCount": 4,
    "source": "youtube",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  },
  {
    "id": 301,
    "slug": "luxun_park",
    "nameKr": "루쉰공원 / 매헌 기념관 (윤봉길 의거지)",
    "nameCn": "鲁迅公园 · 옛 홍커우공원",
    "lat": 31.2702,
    "lng": 121.488,
    "category": "landmark",
    "categoryIconKey": "landmark",
    "tier": "B",
    "icon": "🇰🇷",
    "desc": "수빈 추천 + 캡틴따거 영상. 윤봉길 의사 1932년 4월 29일 폭탄 의거 현장. **매헌(梅軒)** = 윤봉길 의사의 호 — 매헌 기념관(梅軒紀念館). 한국인 필수 코스. 시내에서 30분.",
    "videos": [
      {
        "num": 17,
        "channel": "캡틴따거"
      }
    ],
    "approx": false,
    "imgQuery": "윤봉길 매헌 기념관 鲁迅公园 上海 사적지",
    "weightedScore": null,
    "rawCount": null,
    "source": "suvin+youtube",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  },
  {
    "id": 302,
    "slug": "kprov",
    "nameKr": "대한민국 임시정부 청사",
    "nameCn": "韩国独立运动史迹",
    "lat": 31.223,
    "lng": 121.4733,
    "category": "landmark",
    "categoryIconKey": "landmark",
    "tier": "B",
    "icon": "🇰🇷",
    "desc": "수빈 추천. 황푸구 마당로(馬当路) 306弄 4호. 한국인 여행자 필수 코스. 침착맨 영상에서 디테일 강의. 박명수 영상에서도 방문 (카메라 반입 X).",
    "videos": [
      {
        "num": 1,
        "channel": "할명수"
      },
      {
        "num": 7,
        "channel": "침착맨"
      }
    ],
    "approx": false,
    "imgQuery": "上海 大韩民国临时政府旧址 임시정부 청사 건물 馬当路",
    "weightedScore": null,
    "rawCount": null,
    "source": "suvin+youtube",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  },
  {
    "id": 303,
    "slug": "circus_world",
    "nameKr": "상하이 서커스 월드",
    "nameCn": "Shanghai Circus World",
    "lat": 31.2762,
    "lng": 121.4615,
    "category": "landmark",
    "categoryIconKey": "landmark",
    "tier": "B",
    "icon": "🎪",
    "desc": "수빈 추천. 홍커우구. 잡기·곡예 공연장. 야간 일정 — 예약 필요. ⭐⭐⭐.",
    "videos": [],
    "approx": true,
    "imgQuery": "上海马戏城 Shanghai Circus World 杂技表演 acrobatics show",
    "weightedScore": null,
    "rawCount": null,
    "source": "suvin",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  },
  {
    "id": 304,
    "slug": "qibao",
    "nameKr": "칠보고진 — 수향마을 (七宝古镇)",
    "nameCn": "Qibao Ancient Town · 江南水乡",
    "lat": 31.1639,
    "lng": 121.3494,
    "category": "landmark",
    "categoryIconKey": "landmark",
    "tier": "B",
    "icon": "🛶",
    "desc": "수빈 추천 **강남 수향마을(水乡)** — 운하·돌다리·전통가옥. 민항구 시내 외곽, 반나절 코스. 길거리 음식(취두부·홍샤오러우 만두) + 야경 양호. 좀 멀어서 시내 일정 빡빡하면 판롱티엔디(아래)로 대체 가능.",
    "videos": [],
    "approx": false,
    "imgQuery": "qibao ancient town water canal 七宝古镇",
    "weightedScore": null,
    "rawCount": null,
    "source": "suvin",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  },
  {
    "id": 306,
    "slug": "panlong",
    "nameKr": "판롱티엔디 — 신축 수향마을 (蟠龙天地)",
    "nameCn": "Panlong Tiandi · 인공 수향마을",
    "lat": 31.2098,
    "lng": 121.3068,
    "category": "landmark",
    "categoryIconKey": "landmark",
    "tier": "B",
    "icon": "🛶",
    "desc": "수빈 대안 추천. **홍차오공항 가까운 신축 인공 수향마을**. 칠보고진보다 깔끔/현대적, 카페·디저트 많음. 시내에서 멀지만 홍차오 환승객·반나절 일정에 적합. ⭐⭐⭐.",
    "videos": [],
    "approx": true,
    "imgQuery": "panlong tiandi shanghai water town 蟠龙天地",
    "weightedScore": null,
    "rawCount": null,
    "source": "suvin",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  },
  {
    "id": 206,
    "slug": "ye_shanghai",
    "nameKr": "예상하이 신천지점 (夜上海) — 미쉐린 ★",
    "nameCn": "夜上海 · 新天地店 · Michelin 1-Star",
    "lat": 31.2222,
    "lng": 121.4738,
    "category": "restaurant",
    "categoryIconKey": "utensils",
    "tier": "B",
    "icon": "🦆",
    "desc": "미쉐린 원스타 상하이 본방 중식당. 시그니처 = **북경오리**. 주소: Infinitus Plaza 3F, 168 Hubin Road 黄浦区. 지하철 1호선 Huangpi South Road 도보 12분 / **임시정부 청사 도보 9분** (수빈 통합 추천 위치). ☎ +86 21 6311 2323. [공식 홈페이지](https://www.elite-concepts.com/our-concepts/shanghai/ye-shanghai/)",
    "videos": [],
    "approx": false,
    "imgQuery": "ye shanghai restaurant michelin peking duck 夜上海",
    "weightedScore": null,
    "rawCount": null,
    "source": "user_request",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  },
  {
    "id": 305,
    "slug": "china_art_museum",
    "nameKr": "중화예술궁",
    "nameCn": "中华艺术宫 · China Art Museum",
    "lat": 31.1908,
    "lng": 121.4878,
    "category": "landmark",
    "categoryIconKey": "landmark",
    "tier": "B",
    "icon": "🎨",
    "desc": "수빈 추천. 푸둥. 2010 상하이 엑스포 중국관 건물. 입장료 무료 (예약 필요). ⭐⭐⭐.",
    "videos": [],
    "approx": false,
    "imgQuery": "china art museum shanghai expo 中华艺术宫",
    "weightedScore": null,
    "rawCount": null,
    "source": "suvin",
    "hours": null,
    "closedDays": [],
    "priceRange": null,
    "reservation": null,
    "payment": [],
    "krMenu": null,
    "krReviews": [],
    "day": null
  }
];
  var TIMESTAMPS = {
  "hotel": {},
  "yuyuan": {
    "3": {
      "t": 745,
      "ts_label": "12:25",
      "matched_term": "예원",
      "url": "https://www.youtube.com/watch?v=cgX0ddAtbgY&t=745s",
      "channel": "JTBC Life"
    },
    "5": {
      "t": 134,
      "ts_label": "02:14",
      "matched_term": "예원",
      "url": "https://www.youtube.com/watch?v=rEhSfTXJN7k&t=134s",
      "channel": "육식맨 YOOXICMAN"
    },
    "7": {
      "t": 802,
      "ts_label": "13:22",
      "matched_term": "예원",
      "url": "https://www.youtube.com/watch?v=neiB9XFHMRw&t=802s",
      "channel": "침착맨"
    },
    "9": {
      "t": 354,
      "ts_label": "05:54",
      "matched_term": "예원",
      "url": "https://www.youtube.com/watch?v=jCp1msR_G14&t=354s",
      "channel": "김숙티비kimsookTV"
    },
    "10": {
      "t": 610,
      "ts_label": "10:10",
      "matched_term": "예원",
      "url": "https://www.youtube.com/watch?v=W7nveD5uLMY&t=610s",
      "channel": "또 떠나는 남자 ddoddunam"
    },
    "14": {
      "t": 930,
      "ts_label": "15:30",
      "matched_term": "위원",
      "url": "https://www.youtube.com/watch?v=NUrkL_89TJ0&t=930s",
      "channel": "노마드션 No mad Shaun"
    },
    "17": {
      "t": 870,
      "ts_label": "14:30",
      "matched_term": "예원",
      "url": "https://www.youtube.com/watch?v=NFCqlJop_ls&t=870s",
      "channel": "캡틴따거 Captain Brother"
    }
  },
  "bund": {
    "2": {
      "t": 161,
      "ts_label": "02:41",
      "matched_term": "와이탄",
      "url": "https://www.youtube.com/watch?v=JxAtEaHSehU&t=161s",
      "channel": "걍밍경"
    },
    "3": {
      "t": 390,
      "ts_label": "06:30",
      "matched_term": "와이탄",
      "url": "https://www.youtube.com/watch?v=cgX0ddAtbgY&t=390s",
      "channel": "JTBC Life"
    },
    "5": {
      "t": 367,
      "ts_label": "06:07",
      "matched_term": "와이탄",
      "url": "https://www.youtube.com/watch?v=rEhSfTXJN7k&t=367s",
      "channel": "육식맨 YOOXICMAN"
    },
    "6": {
      "t": 1074,
      "ts_label": "17:54",
      "matched_term": "와이탄",
      "url": "https://www.youtube.com/watch?v=IFalEkvHZAo&t=1074s",
      "channel": "침착맨"
    },
    "7": {
      "t": 3030,
      "ts_label": "50:30",
      "matched_term": "와이탄",
      "url": "https://www.youtube.com/watch?v=neiB9XFHMRw&t=3030s",
      "channel": "침착맨"
    },
    "10": {
      "t": 552,
      "ts_label": "09:12",
      "matched_term": "와이탄",
      "url": "https://www.youtube.com/watch?v=W7nveD5uLMY&t=552s",
      "channel": "또 떠나는 남자 ddoddunam"
    },
    "12": {
      "t": 1084,
      "ts_label": "18:04",
      "matched_term": "와이탄",
      "url": "https://www.youtube.com/watch?v=DFQwLMYT_EA&t=1084s",
      "channel": "캡틴따거 Captain Brother"
    },
    "14": {
      "t": 1846,
      "ts_label": "30:46",
      "matched_term": "와이탄",
      "url": "https://www.youtube.com/watch?v=NUrkL_89TJ0&t=1846s",
      "channel": "노마드션 No mad Shaun"
    },
    "17": {
      "t": 870,
      "ts_label": "14:30",
      "matched_term": "와이탄",
      "url": "https://www.youtube.com/watch?v=NFCqlJop_ls&t=870s",
      "channel": "캡틴따거 Captain Brother"
    }
  },
  "pearl": {
    "2": {
      "t": 669,
      "ts_label": "11:09",
      "matched_term": "동방명주",
      "url": "https://www.youtube.com/watch?v=JxAtEaHSehU&t=669s",
      "channel": "걍밍경"
    },
    "3": {
      "t": 1253,
      "ts_label": "20:53",
      "matched_term": "동방명주",
      "url": "https://www.youtube.com/watch?v=cgX0ddAtbgY&t=1253s",
      "channel": "JTBC Life"
    },
    "5": {
      "t": 373,
      "ts_label": "06:13",
      "matched_term": "동방명주",
      "url": "https://www.youtube.com/watch?v=rEhSfTXJN7k&t=373s",
      "channel": "육식맨 YOOXICMAN"
    },
    "6": {
      "t": 3400,
      "ts_label": "56:40",
      "matched_term": "동방명주",
      "url": "https://www.youtube.com/watch?v=IFalEkvHZAo&t=3400s",
      "channel": "침착맨"
    },
    "7": {
      "t": 150,
      "ts_label": "02:30",
      "matched_term": "동방명주",
      "url": "https://www.youtube.com/watch?v=neiB9XFHMRw&t=150s",
      "channel": "침착맨"
    },
    "10": {
      "t": 799,
      "ts_label": "13:19",
      "matched_term": "동방명주",
      "url": "https://www.youtube.com/watch?v=W7nveD5uLMY&t=799s",
      "channel": "또 떠나는 남자 ddoddunam"
    },
    "12": {
      "t": 612,
      "ts_label": "10:12",
      "matched_term": "동방명주",
      "url": "https://www.youtube.com/watch?v=DFQwLMYT_EA&t=612s",
      "channel": "캡틴따거 Captain Brother"
    },
    "17": {
      "t": 1707,
      "ts_label": "28:27",
      "matched_term": "동방명주",
      "url": "https://www.youtube.com/watch?v=NFCqlJop_ls&t=1707s",
      "channel": "캡틴따거 Captain Brother"
    }
  },
  "shanghai_tower": {
    "6": {
      "t": 3335,
      "ts_label": "55:35",
      "matched_term": "상하이 타워",
      "url": "https://www.youtube.com/watch?v=IFalEkvHZAo&t=3335s",
      "channel": "침착맨"
    },
    "7": {
      "t": 2838,
      "ts_label": "47:18",
      "matched_term": "상하이 타워",
      "url": "https://www.youtube.com/watch?v=neiB9XFHMRw&t=2838s",
      "channel": "침착맨"
    }
  },
  "jinmao": {
    "3": {
      "t": 173,
      "ts_label": "02:53",
      "matched_term": "진마오",
      "url": "https://www.youtube.com/watch?v=cgX0ddAtbgY&t=173s",
      "channel": "JTBC Life"
    },
    "6": {
      "t": 3338,
      "ts_label": "55:38",
      "matched_term": "진마오",
      "url": "https://www.youtube.com/watch?v=IFalEkvHZAo&t=3338s",
      "channel": "침착맨"
    }
  },
  "nanjing_rd": {
    "7": {
      "t": 2,
      "ts_label": "00:02",
      "matched_term": "난징로",
      "url": "https://www.youtube.com/watch?v=neiB9XFHMRw&t=2s",
      "channel": "침착맨"
    }
  },
  "xintiandi": {
    "7": {
      "t": 3849,
      "ts_label": "1:04:09",
      "matched_term": "신천지",
      "url": "https://www.youtube.com/watch?v=neiB9XFHMRw&t=3849s",
      "channel": "침착맨"
    }
  },
  "starbucks": {
    "1": {
      "t": 502,
      "ts_label": "08:22",
      "matched_term": "스타벅스 리저브",
      "url": "https://www.youtube.com/watch?v=832-7C04crk&t=502s",
      "channel": "할명수"
    }
  },
  "renmin_sq": {},
  "wukang": {
    "5": {
      "t": 615,
      "ts_label": "10:15",
      "matched_term": "우캉맨션",
      "url": "https://www.youtube.com/watch?v=rEhSfTXJN7k&t=615s",
      "channel": "육식맨 YOOXICMAN"
    }
  },
  "jesse": {
    "5": {
      "t": 620,
      "ts_label": "10:20",
      "matched_term": "장국영",
      "url": "https://www.youtube.com/watch?v=rEhSfTXJN7k&t=620s",
      "channel": "육식맨 YOOXICMAN"
    }
  },
  "dahuchun": {
    "5": {
      "t": 961,
      "ts_label": "16:01",
      "matched_term": "따후춘",
      "url": "https://www.youtube.com/watch?v=rEhSfTXJN7k&t=961s",
      "channel": "육식맨 YOOXICMAN"
    }
  },
  "local_shengjian": {
    "17": {
      "t": 1768,
      "ts_label": "29:28",
      "matched_term": "성지엔",
      "url": "https://www.youtube.com/watch?v=NFCqlJop_ls&t=1768s",
      "channel": "캡틴따거 Captain Brother"
    }
  },
  "feidachu": {
    "17": {
      "t": 1948,
      "ts_label": "32:28",
      "matched_term": "페이다추",
      "url": "https://www.youtube.com/watch?v=NFCqlJop_ls&t=1948s",
      "channel": "캡틴따거 Captain Brother"
    }
  },
  "diandeqi_yuyuan": {},
  "hanshe": {},
  "nanxiang": {
    "5": {
      "t": 1545,
      "ts_label": "25:45",
      "matched_term": "난샹",
      "url": "https://www.youtube.com/watch?v=rEhSfTXJN7k&t=1545s",
      "channel": "육식맨 YOOXICMAN"
    }
  },
  "haidilao": {
    "1": {
      "t": 1983,
      "ts_label": "33:03",
      "matched_term": "하이디라오",
      "url": "https://www.youtube.com/watch?v=832-7C04crk&t=1983s",
      "channel": "할명수"
    },
    "7": {
      "t": 2262,
      "ts_label": "37:42",
      "matched_term": "하이디라오",
      "url": "https://www.youtube.com/watch?v=neiB9XFHMRw&t=2262s",
      "channel": "침착맨"
    }
  },
  "flair": {},
  "luxun_park": {
    "17": {
      "t": 908,
      "ts_label": "15:08",
      "matched_term": "홍구",
      "url": "https://www.youtube.com/watch?v=NFCqlJop_ls&t=908s",
      "channel": "캡틴따거 Captain Brother"
    }
  },
  "kprov": {
    "1": {
      "t": 1491,
      "ts_label": "24:51",
      "matched_term": "임시정부",
      "url": "https://www.youtube.com/watch?v=832-7C04crk&t=1491s",
      "channel": "할명수"
    },
    "7": {
      "t": 15,
      "ts_label": "00:15",
      "matched_term": "임시정부",
      "url": "https://www.youtube.com/watch?v=neiB9XFHMRw&t=15s",
      "channel": "침착맨"
    }
  },
  "circus_world": {},
  "qibao": {},
  "panlong": {},
  "ye_shanghai": {},
  "china_art_museum": {}
};
  window.__DATA__ = {
    STOPS: STOPS,
    TIMESTAMPS: TIMESTAMPS,
    BUILD_FREEZE_DATE: '2026-05-21',
    BUILD_ID: '8b0619b',
    VARIANT: 'intl'
  };
})();
